# permissions for end users to edit stark8sdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stark8sdeployment-editor-role
rules:
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - stark8sdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - stark8sdeployments/status
  verbs:
  - get
